tarfile: 'tarfiles/{pi,[a-zA-Z]+}_{project,[a-zA-Z]+}_{date,\d{8}}_{prefix}_{subject,[a-zA-Z0-9]+}_{dcmses,\d}.{dcmhash,[A-E0-9]{8}}.tar'

tar_wildcards:
 - pi
 - project
 - date
 - prefix
 - dcmses
 - dcmhash

singularity:
  tar2bids: '/project/6050199/akhanf/singularity/bids-apps/khanlab_tar2bids_v0.1.3.sif'
  gradcorrect: '/project/6050199/akhanf/singularity/bids-apps/khanlab_gradcorrect_v0.0.3.sif'
  fmriprep: '/project/6050199/akhanf/singularity/bids-apps/nipreps_fmriprep_20.2.6.sif'

grad_coeff_file: '/project/ctb-akhanf/akhanf/opt/grad/.coeff_AC84.grad'
